### ISSUE TITLE
feature request: code nav window in sidebar, not editor window

### ISSUE THREAD

**Issue by jasonswearingen** [kdcro101/vscode-typescript-code-navigator#2]
currently codenav opens in the editor window.

I see an extension like [bookmarks](https://github.com/alefragnani/vscode-bookmarks)  displays as a sidebar window, so if you can copy this functionality it would make this extension even more awesome.

**Comment by kdcro101** [comment]
@jasonswearingen,

Sorry for late response.

Thank you for your feedback. 

Reason I've made this extension was because I was not comfortable with having code elements listed on left side. Only way to put (anything) it on right side while having file explorer on left is via webview panel that resembles editor window.

I remember that vscode team released (insiders edition?) `code outline` via activity bar that replaced file explorer when activated which I guess didn't went well with users as they replaced it with `outline` subview in file explorer (still on left).

With activity bar `code outline` you have extra click to make, with subview you have more scrolling to do.
